openapi: 3.0.1
info:
  title: Elm API
  version: 1.0.0
  description: >
    # Introduction

    The elm API has been designed in order to give users access to our collected
    database of user

    information.


    # How to use this API


    # API Keys

    This API relies on an API key for authentication. To generate/access your
    API key please make

    sure that you have opted into the beta by speaking with a representative
    from Elm and that you

    have admin level access to your Elm account. 


    Log in to your account and navigate to Account Settings and click on the API
    tab. On this page

    you will be able to generate an API key, view your key, and regenerate your
    key if your existing

    one is lost or exposed.


    Please note that API keys are sensitive pieces of information and as such
    should be kept secret,

    like a password.


    # Authentication

    Once you have your API key, you can use it for authentication by including
    it in the authorization header of your requests.

    **Headers**

    ```

    Authorization: Token <your token>

    ```

    ## Example request

    This request can be used to test your connection to the API. A successful
    request and authorization will return `{"success":true}`

    ```

    curl --request GET \
      --url http://localhost:3002/api/test/ \
      --header 'Authorization: <your token>'
    ```
  contact:
    email: hello@getelm.co
components:
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: authorization
security:
  - ApiKeyAuth: []
paths:
  /test:
    $ref: paths/test.yaml
  /actions:
    $ref: paths/actions.yaml
  /data/retailers:
    $ref: paths/data@retailers.yaml
  /data/store:
    $ref: paths/data@store.yaml
  /data/sku:
    $ref: paths/data@sku.yaml
